_target_: navsim.agents.token_obs_mlp_agent.TokenObsMLPAgent
_convert_: 'all'

obs_dir: ???
model_module_path: ???
model_class_name: ???
model_config_path: ???

trajectory_sampling:
  _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
  _convert_: 'all'
  num_poses: 8
  interval_length: 0.5
